services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - VITE_ORIGINAL_URL=https://solaceapi.ddnsking.com/api/
    ports:
      - 5173:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
