export enum ROUTES {
  ROOT = '/',
  LOGIN = '/login',
  SIGN_UP = '/sign-up',
  FORGOT_PASSWORD = '/forgot-password',
  VERIFY_CODE = '/verify-code',
  SET_PASSWORD = '/set-password',
  HOME='home',
  STAFF_CALENDAR = '/staff-calendar',
  DASHBOARD = "dashboard",
  CUSTOMER_MANAGEMENT = 'customers-management',
  PRODUCT_MANAGEMNT = 'products-management',
  SERVICES_MANAGEMENT = 'services-management',
  BLOG_MANAGEMENT = 'blog',
  CREATE_BLOG = 'create-blog',
  BLOG_DETAIL = '/blog/:blogId',
  ORDER_MANAGEMENT = 'order',
  PROMOTION_MANAGEMENT = 'promotions-management',
  STAFF_MANAGEMENT = 'staffs-management',
  CREATE_PRODUCT = 'create-product',
  PRODUCT_DETAIL = '/products-management/:productId',
  CREATE_SERVICE = 'create-service',
  SERVICE_DETAIL = '/services-management/:serviceId',
  STAFF_DETAIL = '/staffs-management/:staffId',
  PROMOTION_DETAIL = '/promotions-management/:promotionId',
  CREATE_PROMOTION = 'create-promote',
  ABOUT_US = 'about-us',
  OUR_SERVICES = 'our-services',
  CONTACT = 'contact',
  APPOINMENT_MANAGEMENT = 'appoinments-management',
  SERVICE_CATEGORY = 'service-cate-management',
  SERVICE_CATEGORY_DETAIL = '/service-cate-management/:serviceCategoryId',
  TERMS_AND_POLICIES = '/terms',
  BRANCH_MANAGEMENT = 'branchs-management',
  BRANCH_PROMOTION_MANAGEMENT = 'branch-promotion-management',
  SCHEDULE_MANAGEMENT = 'schedule-management',
  CHAT = 'chat',
  CASHIER_BOOOKING = 'booking-form',
  
  
}
